[platformio]
src_dir = sketch

[env:lilygo-t-dongle-s3]
platform = espressif32
board = lilygo-t-dongle-s3-hid
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
