[platformio]
src_dir = sketch
; Normale Upload-Task nutzt nur USB; OTA bewusst mit -e lilygo-t-dongle-s3-ota
default_envs = lilygo-t-dongle-s3

[env:lilygo-t-dongle-s3]
platform = espressif32
board = lilygo-t-dongle-s3-hid
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0

; OTA-Upload ueber WLAN (Geraet muss bereits OTA-faehige Firmware laufen haben)
[env:lilygo-t-dongle-s3-ota]
extends = env:lilygo-t-dongle-s3
upload_protocol = espota
upload_port = 192.168.1.44
upload_flags =
  --auth=hidsetup123
